apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openclaw-api-keys
  namespace: openclaw
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: openclaw-api-keys
    creationPolicy: Owner
  data:
    - secretKey: GEMINI_API_KEY
      remoteRef:
        key: GEMINI_API_KEY
