apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    targetRevision: 7.*
    helm:
      releaseName: argocd
      valuesObject:
        global:
          domain: argocd.local
        server:
          replicas: 1
        repoServer:
          replicas: 1
        applicationSet:
          replicas: 1
        controller:
          replicas: 1
        redis:
          enabled: true
        redis-ha:
          enabled: false
        configs:
          params:
            server.insecure: true
          cm:
            resource.customizations.ignoreDifferences.apps_Deployment: |
              jsonPointers:
              - /status/terminatingReplicas
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
