apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "40"
spec:
  project: platform
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    targetRevision: 7.*
    helm:
      releaseName: argocd
      valuesObject:
        global:
          domain: argocd-vm.seagull-monster.ts.net
        server:
          replicas: 1
          ingress:
            enabled: true
            ingressClassName: tailscale
            hostname: argocd-vm
            tls: true
        repoServer:
          replicas: 1
        applicationSet:
          replicas: 1
        controller:
          replicas: 1
        redis:
          enabled: true
        redis-ha:
          enabled: false
        configs:
          params:
            server.insecure: true
          cm:
            resource.customizations.ignoreDifferences.apps_Deployment: |
              jsonPointers:
              - /status/terminatingReplicas
            dex.config: |
              connectors:
                - type: google
                  id: google
                  name: Google
                  config:
                    clientID: $argocd-google-sso:clientId
                    clientSecret: $argocd-google-sso:clientSecret
                    redirectURI: https://argocd-vm.seagull-monster.ts.net/api/dex/callback
          rbac:
            policy.default: role:readonly
            policy.csv: |
              g, me@chall.id.au, role:admin
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
