apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-google-sso
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: argocd-google-sso
    creationPolicy: Owner
  data:
    - secretKey: clientId
      remoteRef:
        key: ARGOCD_SSO_GOOGLE_CLIENT_ID
    - secretKey: clientSecret
      remoteRef:
        key: ARGOCD_SSO_GOOGLE_CLIENT_SECRET
    - secretKey: adminEmail
      remoteRef:
        key: ARGOCD_ADMIN_EMAIL
    - secretKey: hostname
      remoteRef:
        key: ARGOCD_HOSTNAME
