apiVersion: v1
kind: Namespace
metadata:
  name: tailscale
  annotations:
    argocd.argoproj.io/sync-wave: "3"
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tailscale-operator-oauth
  namespace: tailscale
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: operator-oauth
    creationPolicy: Owner
  data:
    - secretKey: client_id
      remoteRef:
        key: TAILSCALE_CLIENT_ID
    - secretKey: client_secret
      remoteRef:
        key: TAILSCALE_CLIENT_SECRET
