apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    # This is the Helm chart version (pin it!)
    targetRevision: 9.4.1
    helm:
      releaseName: argocd
      # Start minimal; add values as you need.
      values: |
        global:
          domain: argocd.seagull-monster.ts.net
        configs:
          params:
            server.insecure: true
          cm:
            dex.config: |
              connectors:
                - config:
                    issuer: https://accounts.google.com
                    clientID: $dex.google.clientID
                    clientSecret:  $dex.google.clientSecret
                  type: oidc
                  id: google
                  name: Google
          rbac:
            policy.csv: |
              g, $adminEmail, role:admin
            policy.default: role.readonly
            policy.matchMode: glob
            scopes: '[groups, email]'
        server:
          ingress:
            enabled: true
            ingressClassName: tailscale
            extraTls:
            - hosts:
              - argocd.seagull-monster.ts.net

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true

